repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 50c5478ed9e10bf360335449280cf2a67f4edb7a
    hooks:
      - id: prettier
        args: ['--plugin=@prettier/plugin-php']
        additional_dependencies: ['@prettier/plugin-php@0.18.9']
  - repo: https://github.com/apeschar/pre-commit-phan
    rev: ebd3bfb237c2aceb49fec2198ac69a64209a74a9
    hooks:
      - id: phan
  - repo: local
    hooks:
      - id: phpunit
        name: phpunit
        language: script
        entry: vendor/bin/phpunit test
        files: '[^/]\.php$'
        pass_filenames: false
